import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import './EquipmentDetail.css'; // This path should be relative to your component file


const equipmentData = [
  {
    "id": "1",
    "equipmentType": "CPAP Machine",
    "listings": [
      {
        "equipmentType": "CPAP Machine",
        "model": "Pfizer",
        "count": 12,
        "price": "$75",
        "rentalPeriod": "1 day",
        "supplier": "Trafalgar Hospital"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "ResMed",
        "count": 6,
        "price": "$295",
        "rentalPeriod": "3 days",
        "supplier": "Mercy General"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Philips",
        "count": 12,
        "price": "$176",
        "rentalPeriod": "1 day",
        "supplier": "St. Mary’s Clinic"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Pfizer",
        "count": 12,
        "price": "$182",
        "rentalPeriod": "2 weeks",
        "supplier": "St. Mary’s Clinic"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "ACME",
        "count": 6,
        "price": "$214",
        "rentalPeriod": "2 weeks",
        "supplier": "Mercy General"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Pfizer",
        "count": 8,
        "price": "$360",
        "rentalPeriod": "1 week",
        "supplier": "Trafalgar Hospital"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Pfizer",
        "count": 6,
        "price": "$446",
        "rentalPeriod": "2 days",
        "supplier": "Trillium Care Center"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Philips",
        "count": 1,
        "price": "$54",
        "rentalPeriod": "1 day",
        "supplier": "Trafalgar Hospital"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "ResMed",
        "count": 10,
        "price": "$170",
        "rentalPeriod": "2 weeks",
        "supplier": "Trafalgar Hospital"
      },
      {
        "equipmentType": "CPAP Machine",
        "model": "Philips",
        "count": 12,
        "price": "$416",
        "rentalPeriod": "3 days",
        "supplier": "Riverside Medical"
      }
    ]
  },  
  {
    "id": "2",
    "equipmentType": "ECG Machine",
    "listings": [
      {
        "equipmentType": "ECG Machine",
        "model": "Welch Allyn",
        "count": 13,
        "price": "$178",
        "rentalPeriod": "2 weeks",
        "supplier": "Crestview Rehabilitation"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Zoll",
        "count": 1,
        "price": "$329",
        "rentalPeriod": "1 day",
        "supplier": "Crestview Rehabilitation"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Siemens",
        "count": 3,
        "price": "$181",
        "rentalPeriod": "1 day",
        "supplier": "Harborview Medical"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Bionet",
        "count": 11,
        "price": "$94",
        "rentalPeriod": "1 week",
        "supplier": "Vista Health System"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Siemens",
        "count": 9,
        "price": "$148",
        "rentalPeriod": "2 days",
        "supplier": "Harborview Medical"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "GE",
        "count": 12,
        "price": "$141",
        "rentalPeriod": "2 days",
        "supplier": "Green Valley Clinic"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Zoll",
        "count": 14,
        "price": "$386",
        "rentalPeriod": "1 week",
        "supplier": "City Hospital"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Bionet",
        "count": 9,
        "price": "$196",
        "rentalPeriod": "1 day",
        "supplier": "Crestview Rehabilitation"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Bionet",
        "count": 4,
        "price": "$440",
        "rentalPeriod": "1 day",
        "supplier": "Vista Health System"
      },
      {
        "equipmentType": "ECG Machine",
        "model": "Welch Allyn",
        "count": 13,
        "price": "$496",
        "rentalPeriod": "1 day",
        "supplier": "Crestview Rehabilitation"
      }
    ]
  },
  {'id': '3',
  'equipmentType': 'Spirometers',
  'listings': [{'equipmentType': 'Spirometer',
    'model': 'MIR Spirobank',
    'count': 5,
    'price': '$259',
    'rentalPeriod': '2 weeks',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Spirometer',
    'model': 'SpiroLab',
    'count': 13,
    'price': '$459',
    'rentalPeriod': '1 day',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Spirometer',
    'model': 'MIR Spirobank',
    'count': 10,
    'price': '$489',
    'rentalPeriod': '2 days',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Spirometer',
    'model': 'MIR Spirobank',
    'count': 8,
    'price': '$348',
    'rentalPeriod': '2 weeks',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Spirometer',
    'model': 'Vitalograph',
    'count': 10,
    'price': '$233',
    'rentalPeriod': '2 days',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Spirometer',
    'model': 'MIR Spirobank',
    'count': 4,
    'price': '$297',
    'rentalPeriod': '2 weeks',
    'supplier': 'St. Mary’s Clinic'}]},
 {'id': '4',
  'equipmentType': 'Vacuum Suction Units',
  'listings': [{'equipmentType': 'Vacuum Suction Unit',
    'model': 'SSCOR',
    'count': 7,
    'price': '$389',
    'rentalPeriod': '3 days',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Vacuum Suction Unit',
    'model': 'Laerdal',
    'count': 12,
    'price': '$166',
    'rentalPeriod': '1 day',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Vacuum Suction Unit',
    'model': 'Ambu',
    'count': 8,
    'price': '$464',
    'rentalPeriod': '2 weeks',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Vacuum Suction Unit',
    'model': 'SSCOR',
    'count': 7,
    'price': '$287',
    'rentalPeriod': '1 day',
    'supplier': 'Trillium Care Center'}]},
 {'id': '5',
  'equipmentType': 'Ventilators',
  'listings': [{'equipmentType': 'Ventilator',
    'model': 'Dräger',
    'count': 5,
    'price': '$251',
    'rentalPeriod': '2 days',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Ventilator',
    'model': 'Dräger',
    'count': 15,
    'price': '$200',
    'rentalPeriod': '1 week',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Ventilator',
    'model': 'Hamilton',
    'count': 5,
    'price': '$208',
    'rentalPeriod': '1 week',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Ventilator',
    'model': 'Dräger',
    'count': 8,
    'price': '$479',
    'rentalPeriod': '1 week',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Ventilator',
    'model': 'Hamilton',
    'count': 13,
    'price': '$498',
    'rentalPeriod': '2 weeks',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Ventilator',
    'model': 'ResMed',
    'count': 5,
    'price': '$297',
    'rentalPeriod': '3 days',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Ventilator',
    'model': 'Dräger',
    'count': 7,
    'price': '$85',
    'rentalPeriod': '1 week',
    'supplier': 'St. Mary’s Clinic'}]},
 {'id': '6',
  'equipmentType': 'VR Headsets',
  'listings': [{'equipmentType': 'VR Headset',
    'model': 'HTC Vive',
    'count': 2,
    'price': '$497',
    'rentalPeriod': '2 days',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'VR Headset',
    'model': 'Oculus',
    'count': 14,
    'price': '$424',
    'rentalPeriod': '2 weeks',
    'supplier': 'Mercy General'},
   {'equipmentType': 'VR Headset',
    'model': 'HTC Vive',
    'count': 12,
    'price': '$137',
    'rentalPeriod': '1 week',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'VR Headset',
    'model': 'HTC Vive',
    'count': 14,
    'price': '$469',
    'rentalPeriod': '2 weeks',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'VR Headset',
    'model': 'Oculus',
    'count': 7,
    'price': '$200',
    'rentalPeriod': '1 week',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'VR Headset',
    'model': 'Oculus',
    'count': 7,
    'price': '$403',
    'rentalPeriod': '3 days',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'VR Headset',
    'model': 'HTC Vive',
    'count': 7,
    'price': '$242',
    'rentalPeriod': '1 day',
    'supplier': 'St. Mary’s Clinic'}]},
 {'id': '7',
  'equipmentType': 'Electric Wheelchairs',
  'listings': [{'equipmentType': 'Electric Wheelchair',
    'model': 'Permobil',
    'count': 2,
    'price': '$272',
    'rentalPeriod': '1 day',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Electric Wheelchair',
    'model': 'Permobil',
    'count': 1,
    'price': '$499',
    'rentalPeriod': '2 weeks',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Electric Wheelchair',
    'model': 'Quickie',
    'count': 6,
    'price': '$292',
    'rentalPeriod': '3 days',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Electric Wheelchair',
    'model': 'Permobil',
    'count': 2,
    'price': '$70',
    'rentalPeriod': '2 days',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Electric Wheelchair',
    'model': 'Permobil',
    'count': 12,
    'price': '$298',
    'rentalPeriod': '1 week',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Electric Wheelchair',
    'model': 'Quickie',
    'count': 8,
    'price': '$386',
    'rentalPeriod': '3 days',
    'supplier': 'Trafalgar Hospital'}]},
 {'id': '8',
  'equipmentType': 'Stair Lifts',
  'listings': [{'equipmentType': 'Stair Lift',
    'model': 'Acorn',
    'count': 13,
    'price': '$80',
    'rentalPeriod': '3 days',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Stair Lift',
    'model': 'Stannah',
    'count': 14,
    'price': '$126',
    'rentalPeriod': '1 day',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Stair Lift',
    'model': 'Acorn',
    'count': 2,
    'price': '$298',
    'rentalPeriod': '1 week',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Stair Lift',
    'model': 'Acorn',
    'count': 14,
    'price': '$321',
    'rentalPeriod': '3 days',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Stair Lift',
    'model': 'Stannah',
    'count': 1,
    'price': '$281',
    'rentalPeriod': '2 days',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Stair Lift',
    'model': 'Handicare',
    'count': 9,
    'price': '$425',
    'rentalPeriod': '2 weeks',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Stair Lift',
    'model': 'Handicare',
    'count': 1,
    'price': '$446',
    'rentalPeriod': '2 days',
    'supplier': 'Trillium Care Center'}]},
 {'id': '9',
  'equipmentType': 'Defibrillators',
  'listings': [{'equipmentType': 'Defibrillator',
    'model': 'Cardiac Science',
    'count': 9,
    'price': '$317',
    'rentalPeriod': '3 days',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Defibrillator',
    'model': 'Zoll',
    'count': 6,
    'price': '$425',
    'rentalPeriod': '2 weeks',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Defibrillator',
    'model': 'Cardiac Science',
    'count': 14,
    'price': '$451',
    'rentalPeriod': '1 day',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Defibrillator',
    'model': 'Philips',
    'count': 4,
    'price': '$480',
    'rentalPeriod': '1 day',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Defibrillator',
    'model': 'Cardiac Science',
    'count': 6,
    'price': '$459',
    'rentalPeriod': '2 days',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Defibrillator',
    'model': 'Cardiac Science',
    'count': 11,
    'price': '$385',
    'rentalPeriod': '2 days',
    'supplier': 'Mercy General'}]},
 {'id': '10',
  'equipmentType': 'Ultrasound Machines',
  'listings': [{'equipmentType': 'Ultrasound Machine',
    'model': 'Philips',
    'count': 7,
    'price': '$390',
    'rentalPeriod': '1 day',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Ultrasound Machine',
    'model': 'GE',
    'count': 9,
    'price': '$375',
    'rentalPeriod': '1 day',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Ultrasound Machine',
    'model': 'GE',
    'count': 10,
    'price': '$260',
    'rentalPeriod': '2 weeks',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Ultrasound Machine',
    'model': 'Philips',
    'count': 13,
    'price': '$289',
    'rentalPeriod': '2 days',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Ultrasound Machine',
    'model': 'GE',
    'count': 6,
    'price': '$399',
    'rentalPeriod': '2 days',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Ultrasound Machine',
    'model': 'GE',
    'count': 5,
    'price': '$416',
    'rentalPeriod': '1 week',
    'supplier': 'Trillium Care Center'}]},
 {'id': '11',
  'equipmentType': 'Infusion Pumps',
  'listings': [{'equipmentType': 'Infusion Pump',
    'model': 'Baxter',
    'count': 12,
    'price': '$432',
    'rentalPeriod': '2 weeks',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Baxter',
    'count': 6,
    'price': '$418',
    'rentalPeriod': '1 day',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Medtronic',
    'count': 4,
    'price': '$180',
    'rentalPeriod': '1 week',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Medtronic',
    'count': 13,
    'price': '$339',
    'rentalPeriod': '2 days',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Medtronic',
    'count': 7,
    'price': '$493',
    'rentalPeriod': '2 days',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Medtronic',
    'count': 10,
    'price': '$232',
    'rentalPeriod': '2 weeks',
    'supplier': 'Trafalgar Hospital'},
   {'equipmentType': 'Infusion Pump',
    'model': 'Medtronic',
    'count': 8,
    'price': '$216',
    'rentalPeriod': '2 days',
    'supplier': 'Mercy General'}]},
 {'id': '12',
  'equipmentType': 'Patient Monitors',
  'listings': [{'equipmentType': 'Patient Monitor',
    'model': 'Mindray',
    'count': 8,
    'price': '$223',
    'rentalPeriod': '1 week',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Patient Monitor',
    'model': 'GE',
    'count': 5,
    'price': '$96',
    'rentalPeriod': '2 days',
    'supplier': 'Trillium Care Center'},
   {'equipmentType': 'Patient Monitor',
    'model': 'Mindray',
    'count': 9,
    'price': '$338',
    'rentalPeriod': '3 days',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Patient Monitor',
    'model': 'GE',
    'count': 12,
    'price': '$306',
    'rentalPeriod': '2 weeks',
    'supplier': 'St. Mary’s Clinic'},
   {'equipmentType': 'Patient Monitor',
    'model': 'GE',
    'count': 3,
    'price': '$206',
    'rentalPeriod': '2 days',
    'supplier': 'Mercy General'}]},
 {'id': '13',
  'equipmentType': 'Surgical Lights',
  'listings': [{'equipmentType': 'Surgical Light',
    'model': 'Dräger',
    'count': 14,
    'price': '$295',
    'rentalPeriod': '3 days',
    'supplier': 'Mercy General'},
   {'equipmentType': 'Surgical Light',
    'model': 'Dräger',
    'count': 9,
    'price': '$306',
    'rentalPeriod': '1 week',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Surgical Light',
    'model': 'Dräger',
    'count': 15,
    'price': '$241',
    'rentalPeriod': '2 weeks',
    'supplier': 'Riverside Medical'},
   {'equipmentType': 'Surgical Light',
    'model': 'Maquet',
    'count': 8,
    'price': '$245',
    'rentalPeriod': '2 days',
    'supplier': 'Riverside Medical'}]},
    {'id': '15',
 'equipmentType': 'Hospital Beds',
 'listings': [{'equipmentType': 'Hospital Bed',
   'model': 'Invacare',
   'count': 14,
   'price': '$124',
   'rentalPeriod': '1 day',
   'supplier': 'Health Center'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Invacare',
   'count': 14,
   'price': '$83',
   'rentalPeriod': '3 days',
   'supplier': 'Health Center'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Invacare',
   'count': 4,
   'price': '$275',
   'rentalPeriod': '3 days',
   'supplier': 'General Hospital'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Stryker',
   'count': 3,
   'price': '$344',
   'rentalPeriod': '2 days',
   'supplier': 'Care Facility'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Drive Medical',
   'count': 8,
   'price': '$492',
   'rentalPeriod': '3 days',
   'supplier': 'Medline Industries'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Joerns',
   'count': 15,
   'price': '$136',
   'rentalPeriod': '1 day',
   'supplier': 'General Hospital'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Joerns',
   'count': 8,
   'price': '$299',
   'rentalPeriod': '1 day',
   'supplier': 'General Hospital'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Joerns',
   'count': 4,
   'price': '$278',
   'rentalPeriod': '2 days',
   'supplier': 'Health Center'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Hill-Rom',
   'count': 15,
   'price': '$167',
   'rentalPeriod': '3 days',
   'supplier': 'Care Facility'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Joerns',
   'count': 13,
   'price': '$338',
   'rentalPeriod': '2 days',
   'supplier': 'Sunrise Medical'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Drive Medical',
   'count': 9,
   'price': '$215',
   'rentalPeriod': '2 days',
   'supplier': 'General Hospital'},
  {'equipmentType': 'Hospital Bed',
   'model': 'Joerns',
   'count': 11,
   'price': '$65',
   'rentalPeriod': '1 day',
   'supplier': 'Care Facility'}]}
];


function EquipmentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const equipment = equipmentData.find(item => item.id === id);
  const [sortedListings, setSortedListings] = useState(equipment.listings);

  const sortListings = (field) => {
    const sorted = [...sortedListings].sort((a, b) => {
      let valA = field === 'price' ? Number(a[field].substring(1)) : Number(a[field].split(' ')[0]);
      let valB = field === 'price' ? Number(b[field].substring(1)) : Number(b[field].split(' ')[0]);
      
      return valA - valB;
    });
    setSortedListings(sorted);
  };

  const handleRowClick = (listing) => {
    // This will navigate to the checkout page with the clicked listing's details
    navigate('/checkout', { state: { listing } });
  };

  return (
    <div className="equipment-detail">
      <h1>{equipment.equipmentType} Details</h1>
      <table>
        <thead>
          <tr>
            <th>Model</th>
            <th>Supplier</th>
            <th className="sortable" onClick={() => sortListings('price')}>
              Price  ↑↓<i className="fa fa-sort"></i>
            </th>
            <th className="sortable" onClick={() => sortListings('rentalPeriod')}>
              Delivery Time  ↑↓<i className="fa fa-sort"></i>
            </th>
          </tr>
        </thead>
        <tbody>
          {sortedListings.map((listing, index) => (
            <tr key={index} onClick={() => handleRowClick(listing)} className="clickable-row">
              <td>{listing.model}</td>
              <td>{listing.supplier}</td>
              <td>{listing.price}</td>
              <td>{listing.rentalPeriod}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default EquipmentDetail;